---
- hosts: localhost
  connection: local
  vars:
    wimpy_application_name: "example-app"
    wimpy_application_port: "8080"
    wimpy_aws_region: "eu-west-1"
    wimpy_deployment_environment: "production"
    wimpy_aws_elb_healthcheck_ping_protocol: "tcp"
  roles:
    - wimpy.environment
